const Notification = require('../models/Notification');
const Booking = require('../models/Booking');
const { getMealCutoffInfo } = require('../utils/mealCutoff');

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

const formatDisplayDate = (year, month, day) => {
  const monthName = MONTH_NAMES[month - 1] || 'September';
  return `${monthName} ${day}, ${year}`;
};

/**
 * On-demand generator for student reminders: Checks due meal reminders in IST and creates Notification records.
 */
const autoGenerateDueReminders = async (user) => {
  if (!user || user.role !== 'student' || !user.isActive) return;

  const now = new Date();

  // Compute current IST time & date string (IST = UTC + 5:30)
  const istNowMs = now.getTime() + (5.5 * 3600 * 1000);
  const istNowDate = new Date(istNowMs);
  const todayStr = istNowDate.toISOString().slice(0, 10);
  const [year, month, day] = todayStr.split('-').map(Number);

  // Today UTC midnight Date object
  const todayMealDate = new Date(Date.UTC(year, month - 1, day));
  const formattedTodayDate = formatDisplayDate(year, month, day);

  // Tomorrow UTC midnight Date object
  const tomorrowObj = new Date(Date.UTC(year, month - 1, day + 1));
  const tomorrowStr = tomorrowObj.toISOString().slice(0, 10);
  const [tYear, tMonth, tDay] = tomorrowStr.split('-').map(Number);
  const tomorrowMealDate = new Date(Date.UTC(tYear, tMonth - 1, tDay));
  const formattedTomorrowDate = formatDisplayDate(tYear, tMonth, tDay);

  const reminders = [
    {
      mealType: 'Breakfast',
      triggerHourIST: 21, // 9:00 PM IST previous day
      targetDate: tomorrowMealDate,
      title: "🍳 Tomorrow's Breakfast Reminder",
      message: `Your breakfast is scheduled for ${formattedTomorrowDate}, 7:00 AM – 8:00 AM. Are you going to have breakfast tomorrow?`,
    },
    {
      mealType: 'Lunch',
      triggerHourIST: 7, // 7:00 AM IST
      targetDate: todayMealDate,
      title: '🍛 Lunch Reminder',
      message: `Your lunch is scheduled for ${formattedTodayDate}, 11:00 AM – 1:00 PM. Are you going to have lunch today?`,
    },
    {
      mealType: 'Snacks',
      triggerHourIST: 12, // 12:00 PM IST
      targetDate: todayMealDate,
      title: '☕ Snacks Reminder',
      message: `Your snacks are scheduled for ${formattedTodayDate}, 4:00 PM – 5:00 PM. Are you going to have snacks today?`,
    },
    {
      mealType: 'Dinner',
      triggerHourIST: 15, // 3:00 PM IST
      targetDate: todayMealDate,
      title: '🍽️ Dinner Reminder',
      message: `Your dinner is scheduled for ${formattedTodayDate}, 7:00 PM – 8:00 PM. Are you going to have dinner today?`,
    },
  ];

  for (const r of reminders) {
    const triggerMs = Date.UTC(year, month - 1, day, r.triggerHourIST, 0, 0) - (5.5 * 3600 * 1000);

    if (now.getTime() >= triggerMs) {
      try {
        await Notification.create({
          user: user._id,
          title: r.title,
          message: r.message,
          type: 'meal_reminder',
          mealType: r.mealType,
          date: r.targetDate,
          isRead: false,
        });
      } catch (err) {
        if (err.code !== 11000) {
          console.error('Error generating notification:', err);
        }
      }
    }
  }
};

/**
 * GET /api/notifications
 * Role-aware notification retrieval.
 */
const getNotifications = async (req, res, next) => {
  try {
    if (req.user.role === 'mess_manager' || req.user.role === 'admin') {
      const managerNotifications = await Notification.find({ user: req.user._id })
        .populate('senderStudent', 'name email hostelBlock roomNumber phone')
        .sort({ createdAt: -1 })
        .limit(100);

      const unreadCount = managerNotifications.filter((n) => !n.isRead).length;
      return res.json({ unreadCount, notifications: managerNotifications });
    }

    // Student Role
    await autoGenerateDueReminders(req.user);

    const allNotifications = await Notification.find({ user: req.user._id })
      .sort({ createdAt: -1 })
      .limit(100);

    const skippedBookings = await Booking.find({
      student: req.user._id,
      status: 'skipped',
    });

    const skippedKeys = new Set(
      skippedBookings.map((b) => `${new Date(b.date).toISOString().slice(0, 10)}_${b.mealType}`)
    );

    const actionableNotifications = allNotifications.filter((n) => {
      if (!n.mealType || !n.date) return true;

      const cutoffInfo = getMealCutoffInfo(n.date, n.mealType);
      if (cutoffInfo.isPastCutoff) return false;

      const dateStr = new Date(n.date).toISOString().slice(0, 10);
      const key = `${dateStr}_${n.mealType}`;
      if (skippedKeys.has(key)) return false;

      return true;
    });

    const unreadCount = actionableNotifications.filter((n) => !n.isRead).length;

    res.json({ unreadCount, notifications: actionableNotifications });
  } catch (err) {
    next(err);
  }
};

/**
 * PATCH /api/notifications/:id/read
 * Marks a specific notification as read for req.user._id.
 */
const markNotificationRead = async (req, res, next) => {
  try {
    const notification = await Notification.findOne({ _id: req.params.id, user: req.user._id });
    if (!notification) {
      return res.status(404).json({ message: 'Notification not found' });
    }
    notification.isRead = true;
    await notification.save();
    res.json(notification);
  } catch (err) {
    next(err);
  }
};

module.exports = { getNotifications, markNotificationRead };
